% (C) Copyright Embotech AG, Zurich, Switzerland 2013-2023

function mexDir = build_msgpack_log_parser_mex()
% Builds msgpack-c mex parser in the current file directory
    msgpackcDir = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'dependencies', 'msgpack-c', 'include');
    mex('-O', sprintf('-I%s', msgpackcDir), ...
        sprintf('-I%s', mfilename('fullpath')), ...
        'parse_msgpack_log_mex.cpp', ...
        'mex_msgpack.cpp', ...
        '-output', 'parseMsgPackLog')
    mexDir = mfilename('fullpath');
end