
#ifndef NLP3MINERROR_DTVS_D42F_CASADI_H
#define NLP3MINERROR_DTVS_D42F_CASADI_H

/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

int nlp3minError_DTVs_d42f_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void nlp3minError_DTVs_d42f_objective_1_incref(void);

const casadi_int* nlp3minError_DTVs_d42f_objective_1_sparsity_out(casadi_int i);

int nlp3minError_DTVs_d42f_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void nlp3minError_DTVs_d42f_inequalities_1_incref(void);

const casadi_int* nlp3minError_DTVs_d42f_inequalities_1_sparsity_out(casadi_int i);

int nlp3minError_DTVs_d42f_dynamics_0rd_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void nlp3minError_DTVs_d42f_dynamics_0rd_0_incref(void);

const casadi_int* nlp3minError_DTVs_d42f_dynamics_0rd_0_sparsity_out(casadi_int i);

int nlp3minError_DTVs_d42f_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void nlp3minError_DTVs_d42f_dynamics_0_incref(void);

const casadi_int* nlp3minError_DTVs_d42f_dynamics_0_sparsity_out(casadi_int i);

int nlp3minError_DTVs_d42f_objective_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void nlp3minError_DTVs_d42f_objective_2_incref(void);

const casadi_int* nlp3minError_DTVs_d42f_objective_2_sparsity_out(casadi_int i);

int nlp3minError_DTVs_d42f_inequalities_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void nlp3minError_DTVs_d42f_inequalities_2_incref(void);

const casadi_int* nlp3minError_DTVs_d42f_inequalities_2_sparsity_out(casadi_int i);

int nlp3minError_DTVs_d42f_dynamics_0rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void nlp3minError_DTVs_d42f_dynamics_0rd_1_incref(void);

const casadi_int* nlp3minError_DTVs_d42f_dynamics_0rd_1_sparsity_out(casadi_int i);

int nlp3minError_DTVs_d42f_dynamics_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void nlp3minError_DTVs_d42f_dynamics_1_incref(void);

const casadi_int* nlp3minError_DTVs_d42f_dynamics_1_sparsity_out(casadi_int i);

int nlp3minError_DTVs_d42f_objective_30(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void nlp3minError_DTVs_d42f_objective_30_incref(void);

const casadi_int* nlp3minError_DTVs_d42f_objective_30_sparsity_out(casadi_int i);

int nlp3minError_DTVs_d42f_inequalities_30(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void nlp3minError_DTVs_d42f_inequalities_30_incref(void);

const casadi_int* nlp3minError_DTVs_d42f_inequalities_30_sparsity_out(casadi_int i);

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif
