/*
 *  (C) Copyright Embotech AG, Zurich, Switzerland 2013-2023
 */

/// @file
/// @author embotech AG
/// @date 25 Jun 2021
/// @brief Declaration of Obrttg types in the Simulink autogenerated software modules.

#ifndef _MBOX_OBRTTG_INCLUDE_OBRTTG_TYPES_HPP_
#define _MBOX_OBRTTG_INCLUDE_OBRTTG_TYPES_HPP_

#ifndef BOOLEAN_T
#define BOOLEAN_T unsigned char
#endif // #ifndef BOOLEAN_T
typedef BOOLEAN_T boolean_T;

#ifndef REAL_T
#define REAL_T double
#endif // #ifndef REAL_T
typedef REAL_T real_T;

#ifndef MBOX_PARAMS_N_WAYPOINTS
#define MBOX_PARAMS_N_WAYPOINTS 3
#endif // #ifndef MBOX_PARAMS_N_WAYPOINTS

#ifndef MBOX_PARAMS_DIM_WAYPOINTS
#define MBOX_PARAMS_DIM_WAYPOINTS 6
#endif // #ifndef MBOX_PARAMS_DIM_WAYPOINTS

#ifndef DEFINED_TYPEDEF_FOR_busMboxParameters_
#define DEFINED_TYPEDEF_FOR_busMboxParameters_

typedef struct {
  real_T trackingErrorThreshold;
  real_T waypoints[MBOX_PARAMS_N_WAYPOINTS*MBOX_PARAMS_DIM_WAYPOINTS];
  real_T takeOffHeight;
  real_T verticalTakeOffVelocity[3];
  boolean_T offlineOtpGeneration;
  real_T launchPadPosition[3];
  real_T maxSpeedConstraint;
  real_T tiltAngleConstraint;
  real_T glideSlopeAngleConstraint;
} busMboxParameters;

#endif // #ifndef DEFINED_TYPEDEF_FOR_busMboxParameters_

#ifndef DEFINED_TYPEDEF_FOR_busValidationOptions_
#define DEFINED_TYPEDEF_FOR_busValidationOptions_

// bus validation options bus
typedef struct {
  real_T retargetingEventTime;
} busValidationOptions;

#endif // #ifndef DEFINED_TYPEDEF_FOR_busValidationOptions_

#ifndef DEFINED_TYPEDEF_FOR_busGncParameters_
#define DEFINED_TYPEDEF_FOR_busGncParameters_

typedef struct {
  busMboxParameters gncParameters;
  busValidationOptions validOptionParameters;
} busGncParameters;

#endif // #ifndef DEFINED_TYPEDEF_FOR_busGncParameters_

#ifndef DEFINED_TYPEDEF_FOR_busGncCommIn_
#define DEFINED_TYPEDEF_FOR_busGncCommIn_

typedef struct {
  real_T timestamp_obc;
  real_T timestamp;
  real_T mission_status;
  real_T vehicle_state[17];
  real_T engine_status[16];
} busGncCommIn;

#endif // #ifndef DEFINED_TYPEDEF_FOR_busGncCommIn_

#ifndef DEFINED_TYPEDEF_FOR_busGncCommOut_
#define DEFINED_TYPEDEF_FOR_busGncCommOut_

typedef struct {
  real_T timestamp;
  real_T pac_status;
  real_T position_reference[3];
  real_T velocity_reference[3];
} busGncCommOut;

#endif // #ifndef DEFINED_TYPEDEF_FOR_busGncCommOut_

#ifndef DEFINED_TYPEDEF_FOR_busGncNavigation_
#define DEFINED_TYPEDEF_FOR_busGncNavigation_

typedef struct {
  real_T timestamp;
  real_T position[3];
  real_T velocity[3];
  real_T attitude[4];
  real_T rates[3];
  real_T mass;
  real_T CoM[3];
  boolean_T retargeting_flag;
} busGncNavigation;

#endif // #ifndef DEFINED_TYPEDEF_FOR_busGncNavigation_

#ifndef DEFINED_TYPEDEF_FOR_busGncGuidance_
#define DEFINED_TYPEDEF_FOR_busGncGuidance_

typedef struct {
  real_T timestamp;
  real_T time_to_go;
  real_T state_error[13];
  real_T guidance_reference[17];
  real_T current_optimal_trajectory[540];
} busGncGuidance;

#endif // #ifndef DEFINED_TYPEDEF_FOR_busGncGuidance_

#ifndef DEFINED_TYPEDEF_FOR_busGncController_
#define DEFINED_TYPEDEF_FOR_busGncController_

typedef struct {
  real_T timestamp;
  real_T cmd_propulsion[5];
  real_T engine_on;
} busGncController;

#endif // #ifndef DEFINED_TYPEDEF_FOR_busGncController_

#ifndef DEFINED_TYPEDEF_FOR_busGncOtp_
#define DEFINED_TYPEDEF_FOR_busGncOtp_

typedef struct {
  real_T timestamp;
  real_T optimal_trajectory[540];
  real_T trajectory_id;
  real_T exit_flag;
  real_T n_iter;
  real_T solve_time;
  real_T min_fuel_formulation_flag;
  real_T x_target[13];
  real_T x_start[17];
  real_T health_status[16];
  real_T trajectory_params[3];
} busGncOtp;

#endif // #ifndef DEFINED_TYPEDEF_FOR_busGncOtp_

#ifndef DEFINED_TYPEDEF_FOR_busGncMvm_
#define DEFINED_TYPEDEF_FOR_busGncMvm_

typedef struct {
  real_T timestamp;
  real_T computation_done;
  boolean_T recompute_flag;
  real_T next_target[13];
  real_T next_start[17];
  real_T mission_phase_id[2];
  boolean_T change_trajectory;
  real_T mvm_flags[3];
} busGncMvm;

#endif // #ifndef DEFINED_TYPEDEF_FOR_busGncMvm_

#ifndef DEFINED_TYPEDEF_FOR_busMissionState_
#define DEFINED_TYPEDEF_FOR_busMissionState_

typedef struct {
  real_T time_to_go;
  boolean_T tracking_error_flag;
  boolean_T retargeting_flag;
  boolean_T failure_detection;
} busMissionState;

#endif // #ifndef DEFINED_TYPEDEF_FOR_busMissionState_


#ifndef CONST_REAL_T_NOMINAL_ENGINE_STATUS
#define CONST_REAL_T_NOMINAL_ENGINE_STATUS
static const real_T nominalEngineStatus[15] = {0.0, 112.0, 800.0, -0.1745329251994, 0.1745329251994, 
                                               1.0, 112.0, 800.0, -0.1745329251994, 0.1745329251994,
                                               0.0, 112.0, 800.0, -0.1745329251994, 0.1745329251994};
#endif // #ifndef CONST_REAL_T_NOMINAL_ENGINE_STATUS

#endif // #ifndef _MBOX_OBRTTG_INCLUDE_OBRTTG_TYPES_HPP_